"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/lib/firebase";
import { listSubscriptions, type Subscription, updateSubscription } from "@/lib/subscriptionService";
import { getSubscriptionEndDate } from "@/lib/subscriptionScheduling";
import { getPlan } from "@/lib/subscriptionData";
import { getOrders, updateOrderStatus } from "@/lib/orderService";
import type { Order } from "@/types/order";
import { DELIVERY_SLOTS, DELIVERY_SLOT_CAPACITY, getDeliverySlotCounts } from "@/lib/deliverySlotService";

type DeliveryStatus = "PENDING" | "DELIVERED";
type DeliveryRow = { id:string; source:"SUBSCRIPTION"|"SCHEDULED_MEAL"|"ORDER"; customerName:string; customerId:string; phone:string; planOrType:string; meal:string; protein?:number; instructions?:string; time:string; address:string; status:DeliveryStatus; orderId?:string; subscriptionId?:string; skipId?:string };
const records = (s:Subscription) => s.skippedMealRecords || [];
const statusMap = (s:Subscription) => (s as Subscription & {deliveryStatusByDate?:Record<string,DeliveryStatus>}).deliveryStatusByDate || {};
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
const localDate = (value:string) => { const d = new Date(value); if (Number.isNaN(d.getTime())) return value.slice(0,10); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
const weekday = () => ["SUN","MON","TUE","WED","THU","FRI","SAT"][new Date().getDay()];
const locationHref = (value:string) => { const v=(value||"").trim(); if(!v) return ""; if(/^https?:\/\//i.test(v)) return v; return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(v)}`; };
function LocationCell({value}:{value?:string}){ const v=(value||"").trim(); if(!v) return <span>—</span>; const href=locationHref(v); return <a href={href} target="_blank" rel="noopener noreferrer" className="text-blue-300 underline decoration-blue-300/50 underline-offset-2 hover:text-blue-200">Open in Google Maps</a>; }
function subscriptionEligibleToday(s:Subscription,todayDate:string){
  if(!s.startDate) return false;
  const first = new Date(s.startDate);
  if(Number.isNaN(first.getTime())) return false;
  const end = s.endDate ? new Date(s.endDate) : getSubscriptionEndDate(first);
  if(Number.isNaN(end.getTime())) return false;
  return todayDate >= localDate(s.startDate) && todayDate <= localDate(end.toISOString()) && new Date(`${todayDate}T00:00:00`).getDay()!==0;
}

export default function AdminOperationsPage(){
 const [checking,setChecking]=useState(true),[loading,setLoading]=useState(true),[subs,setSubs]=useState<Subscription[]>([]),[pendingSubscriptions,setPendingSubscriptions]=useState<Subscription[]>([]),[orders,setOrders]=useState<Order[]>([]),[counts,setCounts]=useState<Record<string,number>>({}),[message,setMessage]=useState("");
 async function load(){setLoading(true);try{const [allSubscriptions,o,c]=await Promise.all([listSubscriptions(),getOrders(),getDeliverySlotCounts()]);setSubs(allSubscriptions.filter(x=>x.status==="ACTIVE"));setPendingSubscriptions(allSubscriptions.filter(x=>x.status==="PENDING_PAYMENT"));setOrders(o);setCounts(c);}catch(e){console.error(e);setMessage("Unable to load operations data.")}finally{setLoading(false)}}
 useEffect(()=>onAuthStateChanged(auth,u=>{if(!u)window.location.href="/login";else{setChecking(false);load()}}),[]);
 const date=today(), day=weekday();
 const scheduled=useMemo(()=>subs.flatMap(s=>records(s).filter(r=>r.status==="SCHEDULED"&&r.scheduledFor===date).map(r=>({s,r}))),[subs,date]);
 const skipped=useMemo(()=>subs.flatMap(s=>records(s).map(r=>({s,r}))),[subs]);
 const eligibleSubs=subs.filter(s=>subscriptionEligibleToday(s,date));
 const subscriberRows:DeliveryRow[]=eligibleSubs.filter(s=>!records(s).some(r=>localDate(r.skippedAt)===date&&r.status!=="USED"&&r.status!=="EXPIRED")).map(s=>{const meal=getPlan(s.planId)?.meals[day.toLowerCase()];const custom=(s.mealCustomizations||{})[day];const override=s.deliverySlotOverrides?.[date];return{id:`sub:${s.id}:${date}`,source:"SUBSCRIPTION" as const,customerName:s.customerName||"Customer",customerId:s.userId,phone:s.phone||"—",planOrType:`${s.planName} Subscription`,meal:meal?.name||"Today's subscription meal",protein:custom?.protein ?? s.proteinPerMeal,instructions:s.instructions,time:override||s.deliverySlot||s.deliveryTime,address:s.address,status:statusMap(s)[date]||"PENDING",subscriptionId:s.id}}).filter(x=>x.status!=="DELIVERED");
 const scheduledRows:DeliveryRow[]=scheduled.filter(({s})=>subscriptionEligibleToday(s,date)).map(({s,r})=>({id:`skip:${s.id}:${r.id}`,source:"SCHEDULED_MEAL" as const,customerName:s.customerName||"Customer",customerId:s.userId,phone:s.phone||"—",planOrType:`${s.planName} Scheduled Meal`,meal:"Previously skipped meal",protein:s.proteinPerMeal,instructions:s.instructions,time:r.scheduledTime||s.deliverySlot||s.deliveryTime,address:s.address,status:statusMap(s)[`${date}:${r.id}`]||"PENDING",subscriptionId:s.id,skipId:r.id})).filter(x=>x.status!=="DELIVERED");
 const orderRows:DeliveryRow[]=orders.filter(o=>o.status!=="DELIVERED"&&o.status!=="CANCELLED").map(o=>({id:`order:${o.id}`,source:"ORDER" as const,customerName:o.name,customerId:o.id||o.orderId,phone:o.phone,planOrType:"Normal Menu Order",meal:o.items.map(i=>`${i.name} × ${i.quantity}`).join(", "),time:"Normal order",address:o.address||o.location,status:"PENDING",orderId:o.id}));
 const deliveries=[...subscriberRows,...scheduledRows,...orderRows];
 const delivered:DeliveryRow[]=[...eligibleSubs.flatMap(s=>{const rows:DeliveryRow[]=[];const m=getPlan(s.planId)?.meals[day.toLowerCase()];const custom=(s.mealCustomizations||{})[day];const override=s.deliverySlotOverrides?.[date];if(statusMap(s)[date]==="DELIVERED")rows.push({id:`sub:${s.id}:${date}`,source:"SUBSCRIPTION",customerName:s.customerName||"Customer",customerId:s.userId,phone:s.phone||"—",planOrType:`${s.planName} Subscription`,meal:m?.name||"Today's subscription meal",protein:custom?.protein ?? s.proteinPerMeal,instructions:s.instructions,time:override||s.deliverySlot||s.deliveryTime,address:s.address,status:"DELIVERED",subscriptionId:s.id});records(s).filter(r=>r.status==="SCHEDULED"&&r.scheduledFor===date&&statusMap(s)[`${date}:${r.id}`]==="DELIVERED").forEach(r=>rows.push({id:`skip:${s.id}:${r.id}`,source:"SCHEDULED_MEAL",customerName:s.customerName||"Customer",customerId:s.userId,phone:s.phone||"—",planOrType:`${s.planName} Scheduled Meal`,meal:"Previously skipped meal",protein:s.proteinPerMeal,instructions:s.instructions,time:r.scheduledTime||s.deliverySlot||s.deliveryTime,address:s.address,status:"DELIVERED",subscriptionId:s.id,skipId:r.id}));return rows}),...orders.filter(o=>o.status==="DELIVERED").map(o=>({id:`order:${o.id}`,source:"ORDER" as const,customerName:o.name,customerId:o.id||o.orderId,phone:o.phone,planOrType:"Normal Menu Order",meal:o.items.map(i=>`${i.name} × ${i.quantity}`).join(", "),time:"Delivered",address:o.address||o.location,status:"DELIVERED" as const,orderId:o.id}))];
 async function changeStatus(row:DeliveryRow,status:DeliveryStatus){try{if(row.source==="ORDER"&&row.orderId)await updateOrderStatus(row.orderId,status==="DELIVERED"?"DELIVERED":"CONFIRMED");else if(row.subscriptionId){const s=subs.find(x=>x.id===row.subscriptionId);if(!s)return;const map=statusMap(s);const key=row.source==="SUBSCRIPTION"?date:`${date}:${row.skipId}`;await updateSubscription(s.id!,{deliveryStatusByDate:{...map,[key]:status}} as Partial<Subscription>)}setMessage(status==="DELIVERED"?"Delivery moved to Delivered.":"Delivery returned to Pending.");await load()}catch(e){console.error(e);setMessage("Unable to update delivery status.")}}
 async function confirmSubscription(item:Subscription){if(!item.id)return;setLoading(true);setMessage("");try{const confirmationTime=new Date();const firstDelivery=item.startDate?new Date(item.startDate):confirmationTime;const end=item.endDate?new Date(item.endDate):getSubscriptionEndDate(firstDelivery);await updateSubscription(item.id,{status:"ACTIVE",paymentStatus:"SUCCESS",paymentVerifiedAt:confirmationTime.toISOString(),startDate:firstDelivery.toISOString(),endDate:end.toISOString()});setMessage(`${item.customerName||"Customer"} subscription confirmed.`);await load()}catch(e){console.error(e);setMessage("Unable to confirm subscription.")}finally{setLoading(false)}}
 async function rejectSubscription(item:Subscription){if(!item.id)return;if(!window.confirm(`Reject payment for ${item.customerName||"this customer"}?`))return;setLoading(true);setMessage("");try{await updateSubscription(item.id,{status:"CANCELLED",paymentStatus:"FAILED",paymentFailedAt:new Date().toISOString()});setMessage(`${item.customerName||"Customer"} subscription rejected.`);await load()}catch(e){console.error(e);setMessage("Unable to reject subscription.")}finally{setLoading(false)}}
 if(checking||loading)return <main className="min-h-screen grid place-items-center bg-[#0F0F10] text-white/50">Loading admin operations…</main>;
 return <main className="min-h-screen bg-[#0F0F10] px-5 py-8 text-white md:px-10"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#E63946]">Admin Operations</p><h1 className="mt-2 text-4xl font-bold">Delivery Control</h1><p className="mt-2 text-white/40">Active subscribers, today's deliveries and completed deliveries.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin" className="rounded-full border border-white/10 px-5 py-2 text-sm">Restaurant Admin</Link><Link href="/admin/restaurant-status" className="rounded-full border border-white/10 px-5 py-2 text-sm">Restaurant Status</Link><Link href="/admin/orders" className="rounded-full border border-white/10 px-5 py-2 text-sm">Orders</Link><Link href="/admin/subscriptions" className="rounded-full bg-[#E63946] px-5 py-2 text-sm font-bold">Subscriptions</Link></div></header>
 <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Stat label="Active subscribers" value={subs.length}/><Stat label="Subscriptions to confirm" value={pendingSubscriptions.length}/><Stat label="Today's deliveries" value={deliveries.length}/><Stat label="Skipped credits" value={skipped.filter(x=>x.r.status==="AVAILABLE").length}/><Stat label="Delivered today" value={delivered.length}/></div>{message&&<div className="mt-5 rounded-xl border border-white/10 bg-white/5 p-4 text-sm text-white/70">{message}</div>}
 <section className="mt-8 rounded-3xl border border-yellow-500/20 bg-[#171717] p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">Subscriptions to be Confirmed</h2><p className="mt-1 text-sm text-white/40">Check the UPI payment, then confirm or reject the subscription.</p></div><span className="rounded-full bg-yellow-500/10 px-3 py-1 text-xs text-yellow-300">{pendingSubscriptions.length} pending</span></div><div className="mt-5 space-y-3">{pendingSubscriptions.map(x=><div key={x.id} className="rounded-2xl border border-white/10 bg-black/20 p-5"><div className="grid gap-5 lg:grid-cols-[1.2fr_1fr_1fr_auto] lg:items-center"><div><p className="font-bold">{x.customerName||"Customer"}</p><p className="mt-1 text-sm text-white/55">{x.phone||"—"}</p></div><div><p className="text-xs text-white/35">Plan</p><p className="mt-1 font-semibold">{x.planName}</p><p className="text-xs text-white/40">₹{x.amount}/week</p></div><div><p className="text-xs text-white/35">Delivery</p><p className="mt-1">{x.deliverySlot||x.deliveryTime}</p><p className="text-xs text-white/40">{x.address||"No address"}</p>{x.upiTransactionId&&<p className="mt-3 rounded-xl border border-blue-500/20 bg-blue-500/10 p-3 text-xs"><span className="font-bold text-blue-300">UPI Transaction ID / UTR:</span> <span className="font-mono text-white">{x.upiTransactionId}</span></p>}</div><div className="flex gap-2"><button disabled={loading} onClick={()=>confirmSubscription(x)} className="rounded-xl bg-green-600 px-4 py-3 text-xs font-bold disabled:opacity-50">✓ Confirm</button><button disabled={loading} onClick={()=>rejectSubscription(x)} className="rounded-xl border border-red-500/30 px-4 py-3 text-xs font-bold text-red-300 disabled:opacity-50">Reject</button></div></div>{x.instructions&&<div className="mt-4 border-t border-white/5 pt-3 text-sm text-white/55"><b className="text-white/75">Special instructions:</b> {x.instructions}</div>}</div>)}{pendingSubscriptions.length===0&&<p className="p-5 text-white/40">No subscriptions waiting for confirmation.</p>}</div></section>
 <section className="mt-8 rounded-3xl border border-white/10 bg-[#171717] p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">Subscribers</h2><p className="text-sm text-white/40">Active members only. Pending payments and failed checkouts are excluded.</p></div><div className="flex flex-wrap gap-2">{DELIVERY_SLOTS.map(s=><div key={s} className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-xs"><b>{s}</b><span className="ml-2 text-white/45">{counts[s]||0}/{DELIVERY_SLOT_CAPACITY}</span>{(counts[s]||0)>=DELIVERY_SLOT_CAPACITY&&<span className="ml-2 text-red-300">FULL</span>}</div>)}</div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-xs text-white/35"><tr><th className="p-3">Customer</th><th className="p-3">ID</th><th className="p-3">Phone</th><th className="p-3">Plan</th><th className="p-3">Slot</th><th className="p-3">Location</th><th className="p-3">Status</th></tr></thead><tbody>{subs.map(s=><tr key={s.id} className="border-t border-white/5"><td className="p-3 font-semibold">{s.customerName||"Customer"}</td><td className="p-3 text-white/45">{s.userId}</td><td className="p-3">{s.phone||"—"}</td><td className="p-3">{s.planName}</td><td className="p-3">{s.deliverySlot||s.deliveryTime}</td><td className="max-w-[260px] p-3"><LocationCell value={s.address}/></td><td className="p-3 text-green-300">ACTIVE</td></tr>)}</tbody></table>{subs.length===0&&<p className="p-5 text-white/40">No active subscribers.</p>}</div></section>
 <section className="mt-8 rounded-3xl border border-white/10 bg-[#171717] p-6"><h2 className="text-2xl font-bold">Today's Deliveries</h2><p className="mt-1 text-sm text-white/40">Subscriber meals, scheduled skipped meals and normal menu orders that still need delivery today.</p><DeliveryTable rows={deliveries} onStatus={changeStatus}/></section>
 <section className="mt-8 rounded-3xl border border-white/10 bg-[#171717] p-6"><h2 className="text-2xl font-bold">Delivered</h2><p className="mt-1 text-sm text-white/40">Completed deliveries are kept here for today's history.</p><DeliveryTable rows={delivered} onStatus={changeStatus}/></section>
 <section className="mt-8 grid gap-8 lg:grid-cols-2"><ListCard title="Skipped Meals" items={skipped.filter(x=>x.r.status==="AVAILABLE").map(x=>`${x.s.customerName||"Customer"} · ${x.s.planName} · skipped ${localDate(x.r.skippedAt)}`)}/><ListCard title="Rescheduled Meals" items={skipped.filter(x=>x.r.status==="SCHEDULED").map(x=>`${x.s.customerName||"Customer"} · scheduled for ${x.r.scheduledFor||"—"} · ${x.r.scheduledTime||x.s.deliverySlot||x.s.deliveryTime}`)}/></section>
 </div></main>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-[#171717] p-5"><p className="text-xs text-white/40">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>}
function ListCard({title,items}:{title:string;items:string[]}){return <div className="rounded-3xl border border-white/10 bg-[#171717] p-6"><h2 className="text-2xl font-bold">{title}</h2><div className="mt-5 space-y-2">{items.length?items.map((x,i)=><div key={`${x}-${i}`} className="rounded-xl border border-white/10 bg-black/20 p-4 text-sm text-white/65">{x}</div>):<p className="text-white/35">None.</p>}</div></div>}
function DeliveryTable({rows,onStatus}:{rows:DeliveryRow[];onStatus:(row:DeliveryRow,status:DeliveryStatus)=>void}){return <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="text-xs text-white/35"><tr><th className="p-3">Customer</th><th className="p-3">Type</th><th className="p-3">Meal</th><th className="p-3">Protein</th><th className="p-3">Slot</th><th className="p-3">Address</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-white/5 align-top"><td className="p-3"><p className="font-semibold">{row.customerName}</p><p className="mt-1 text-xs text-white/40">{row.phone}</p></td><td className="p-3">{row.planOrType}</td><td className="p-3"><p>{row.meal}</p>{row.instructions&&<p className="mt-1 text-xs text-white/40">{row.instructions}</p>}</td><td className="p-3">{row.protein?`${row.protein}g`:"—"}</td><td className="p-3">{row.time}</td><td className="max-w-[280px] p-3"><LocationCell value={row.address}/></td><td className="p-3">{row.status}</td><td className="p-3"><button onClick={()=>onStatus(row,row.status==="DELIVERED"?"PENDING":"DELIVERED")} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-semibold">{row.status==="DELIVERED"?"Mark Pending":"Mark Delivered"}</button></td></tr>)}</tbody></table>{rows.length===0&&<p className="p-5 text-white/40">None.</p>}</div>}
