"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/lib/firebase";
import { listSubscriptions, type Subscription, updateSubscription } from "@/lib/subscriptionService";
import { getPlan } from "@/lib/subscriptionData";
import { getOrders, updateOrderStatus } from "@/lib/orderService";
import type { Order } from "@/types/order";
import { DELIVERY_SLOTS, DELIVERY_SLOT_CAPACITY, getDeliverySlotCounts } from "@/lib/deliverySlotService";

type DeliveryStatus = "PENDING" | "DELIVERED";
type DeliveryRow = { id:string; source:"SUBSCRIPTION"|"SCHEDULED_MEAL"|"ORDER"; customerName:string; customerId:string; phone:string; planOrType:string; meal:string; time:string; address:string; status:DeliveryStatus; orderId?:string; subscriptionId?:string; skipId?:string };
const records = (s:Subscription) => s.skippedMealRecords || [];
const statusMap = (s:Subscription) => (s as Subscription & {deliveryStatusByDate?:Record<string,DeliveryStatus>}).deliveryStatusByDate || {};
const today = () => { const d = new Date(); const y = d.getFullYear(); const m = String(d.getMonth()+1).padStart(2,"0"); const day = String(d.getDate()).padStart(2,"0"); return `${y}-${m}-${day}`; };
const localDate = (value:string) => { const d = new Date(value); const y = d.getFullYear(); const m = String(d.getMonth()+1).padStart(2,"0"); const day = String(d.getDate()).padStart(2,"0"); return `${y}-${m}-${day}`; };
const weekday = () => ["SUN","MON","TUE","WED","THU","FRI","SAT"][new Date().getDay()];

export default function AdminOperationsPage(){
 const [checking,setChecking]=useState(true),[loading,setLoading]=useState(true),[subs,setSubs]=useState<Subscription[]>([]),[orders,setOrders]=useState<Order[]>([]),[counts,setCounts]=useState<Record<string,number>>({}),[message,setMessage]=useState("");
 async function load(){setLoading(true);try{const [s,o,c]=await Promise.all([listSubscriptions(),getOrders(),getDeliverySlotCounts()]);setSubs(s.filter(x=>x.status==="ACTIVE"));setOrders(o);setCounts(c);}catch(e){console.error(e);setMessage("Unable to load operations data.")}finally{setLoading(false)}}
 useEffect(()=>onAuthStateChanged(auth,u=>{if(!u)window.location.href="/login";else{setChecking(false);load()}}),[]);
 const date=today(), day=weekday();
 const scheduled=useMemo(()=>subs.flatMap(s=>records(s).filter(r=>r.status==="SCHEDULED"&&r.scheduledFor===date).map(r=>({s,r}))),[subs,date]);
 const skipped=useMemo(()=>subs.flatMap(s=>records(s).map(r=>({s,r}))),[subs]);
 const subscriberRows:DeliveryRow[]=subs.filter(s=>!records(s).some(r=>localDate(r.skippedAt)===date&&r.status!=="USED"&&r.status!=="EXPIRED")).map(s=>{const meal=getPlan(s.planId)?.meals[day.toLowerCase()];return{id:`sub:${s.id}:${date}`,source:"SUBSCRIPTION" as const,customerName:s.customerName||"Customer",customerId:s.userId,phone:s.phone||"—",planOrType:`${s.planName} Subscription`,meal:meal?.name||"Today's subscription meal",time:s.deliverySlot||s.deliveryTime,address:s.address,status:statusMap(s)[date]||"PENDING",subscriptionId:s.id}}).filter(x=>x.status!=="DELIVERED");
 const scheduledRows:DeliveryRow[]=scheduled.map(({s,r})=>({id:`skip:${s.id}:${r.id}`,source:"SCHEDULED_MEAL" as const,customerName:s.customerName||"Customer",customerId:s.userId,phone:s.phone||"—",planOrType:`${s.planName} Scheduled Meal`,meal:"Previously skipped meal",time:r.scheduledTime||s.deliverySlot||s.deliveryTime,address:s.address,status:statusMap(s)[`${date}:${r.id}`]||"PENDING",subscriptionId:s.id,skipId:r.id})).filter(x=>x.status!=="DELIVERED");
 const orderRows:DeliveryRow[]=orders.filter(o=>o.status!=="DELIVERED"&&o.status!=="CANCELLED").map(o=>({id:`order:${o.id}`,source:"ORDER" as const,customerName:o.name,customerId:o.id||o.orderId,phone:o.phone,planOrType:"Normal Menu Order",meal:o.items.map(i=>`${i.name} × ${i.quantity}`).join(", "),time:"Normal order",address:o.address||o.location,status:"PENDING",orderId:o.id}));
 const deliveries=[...subscriberRows,...scheduledRows,...orderRows];
 const delivered:DeliveryRow[]=[...subs.flatMap(s=>{const rows:DeliveryRow[]=[];const m=getPlan(s.planId)?.meals[day.toLowerCase()];if(statusMap(s)[date]==="DELIVERED")rows.push({id:`sub:${s.id}:${date}`,source:"SUBSCRIPTION",customerName:s.customerName||"Customer",customerId:s.userId,phone:s.phone||"—",planOrType:`${s.planName} Subscription`,meal:m?.name||"Today's subscription meal",time:s.deliverySlot||s.deliveryTime,address:s.address,status:"DELIVERED",subscriptionId:s.id});records(s).filter(r=>r.status==="SCHEDULED"&&r.scheduledFor===date&&statusMap(s)[`${date}:${r.id}`]==="DELIVERED").forEach(r=>rows.push({id:`skip:${s.id}:${r.id}`,source:"SCHEDULED_MEAL",customerName:s.customerName||"Customer",customerId:s.userId,phone:s.phone||"—",planOrType:`${s.planName} Scheduled Meal`,meal:"Previously skipped meal",time:r.scheduledTime||s.deliverySlot||s.deliveryTime,address:s.address,status:"DELIVERED",subscriptionId:s.id,skipId:r.id}));return rows}),...orders.filter(o=>o.status==="DELIVERED").map(o=>({id:`order:${o.id}`,source:"ORDER" as const,customerName:o.name,customerId:o.id||o.orderId,phone:o.phone,planOrType:"Normal Menu Order",meal:o.items.map(i=>`${i.name} × ${i.quantity}`).join(", "),time:"Delivered",address:o.address||o.location,status:"DELIVERED" as const,orderId:o.id}))];
 async function changeStatus(row:DeliveryRow,status:DeliveryStatus){try{if(row.source==="ORDER"&&row.orderId)await updateOrderStatus(row.orderId,status==="DELIVERED"?"DELIVERED":"CONFIRMED");else if(row.subscriptionId){const s=subs.find(x=>x.id===row.subscriptionId);if(!s)return;const map=statusMap(s);const key=row.source==="SUBSCRIPTION"?date:`${date}:${row.skipId}`;await updateSubscription(s.id!,{deliveryStatusByDate:{...map,[key]:status}} as Partial<Subscription>)}setMessage(status==="DELIVERED"?"Delivery moved to Delivered.":"Delivery returned to Pending.");await load()}catch(e){console.error(e);setMessage("Unable to update delivery status.")}}
 if(checking||loading)return <main className="min-h-screen grid place-items-center bg-[#0F0F10] text-white/50">Loading admin operations…</main>;
 return <main className="min-h-screen bg-[#0F0F10] px-5 py-8 text-white md:px-10"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#E63946]">Admin Operations</p><h1 className="mt-2 text-4xl font-bold">Delivery Control</h1><p className="mt-2 text-white/40">Active subscribers, today's deliveries and completed deliveries.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin" className="rounded-full border border-white/10 px-5 py-2 text-sm">Restaurant Admin</Link><Link href="/admin/restaurant-status" className="rounded-full border border-white/10 px-5 py-2 text-sm">Restaurant Status</Link><Link href="/admin/orders" className="rounded-full border border-white/10 px-5 py-2 text-sm">Orders</Link></div></header>
 <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Active subscribers" value={subs.length}/><Stat label="Today's deliveries" value={deliveries.length}/><Stat label="Skipped credits" value={skipped.filter(x=>x.r.status==="AVAILABLE").length}/><Stat label="Delivered today" value={delivered.length}/></div>{message&&<div className="mt-5 rounded-xl border border-white/10 bg-white/5 p-4 text-sm text-white/70">{message}</div>}
 <section className="mt-8 rounded-3xl border border-white/10 bg-[#171717] p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">Subscribers</h2><p className="text-sm text-white/40">Active members only. Pending payments and failed checkouts are excluded.</p></div><div className="flex flex-wrap gap-2">{DELIVERY_SLOTS.map(s=><div key={s} className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-xs"><b>{s}</b><span className="ml-2 text-white/45">{counts[s]||0}/{DELIVERY_SLOT_CAPACITY}</span>{(counts[s]||0)>=DELIVERY_SLOT_CAPACITY&&<span className="ml-2 text-red-300">FULL</span>}</div>)}</div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-xs text-white/35"><tr><th className="p-3">Customer</th><th className="p-3">ID</th><th className="p-3">Phone</th><th className="p-3">Plan</th><th className="p-3">Slot</th><th className="p-3">Location</th><th className="p-3">Status</th></tr></thead><tbody>{subs.map(s=><tr key={s.id} className="border-t border-white/5"><td className="p-3 font-semibold">{s.customerName||"Customer"}</td><td className="p-3 text-white/45">{s.userId}</td><td className="p-3">{s.phone||"—"}</td><td className="p-3">{s.planName}</td><td className="p-3">{s.deliverySlot||s.deliveryTime}</td><td className="max-w-[260px] p-3">{s.address}</td><td className="p-3 text-green-300">ACTIVE</td></tr>)}</tbody></table>{subs.length===0&&<p className="p-5 text-white/40">No active subscribers.</p>}</div></section>
 <section className="mt-8 rounded-3xl border border-white/10 bg-[#171717] p-6"><h2 className="text-2xl font-bold">Today's Deliveries</h2><p className="mt-1 text-sm text-white/40">Subscriber meals, scheduled skipped meals and normal menu orders that still need delivery today.</p><DeliveryTable rows={deliveries} onStatus={changeStatus}/></section>
 <section className="mt-8 rounded-3xl border border-white/10 bg-[#171717] p-6"><h2 className="text-2xl font-bold">Delivered</h2><p className="mt-1 text-sm text-white/40">Completed deliveries are kept here for today's history.</p><DeliveryTable rows={delivered} onStatus={changeStatus}/></section>
 <section className="mt-8 grid gap-8 lg:grid-cols-2"><ListCard title="Skipped Meals" items={skipped.filter(x=>x.r.status==="AVAILABLE").map(x=>`${x.s.customerName||"Customer"} · ${x.s.planName} · skipped ${localDate(x.r.skippedAt)}`)}/><ListCard title="Rescheduled Meals" items={skipped.filter(x=>x.r.status==="SCHEDULED").map(x=>`${x.s.customerName||"Customer"} · scheduled for ${x.r.scheduledFor||"—"} · ${x.r.scheduledTime||x.s.deliverySlot||x.s.deliveryTime}`)}/></section>
 </div></main>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-[#171717] p-5"><p className="text-xs text-white/40">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>}
function ListCard({title,items}:{title:string;items:string[]}){return <div className="rounded-3xl border border-white/10 bg-[#171717] p-6"><h2 className="text-2xl font-bold">{title}</h2><div className="mt-5 space-y-2">{items.length?items.map((x,i)=><div key={`${x}-${i}`} className="rounded-xl border border-white/10 bg-black/20 p-4 text-sm text-white/65">{x}</div>):<p className="text-white/35">None.</p>}</div></div>}
function DeliveryTable({rows,onStatus}:{rows:DeliveryRow[];onStatus:(r:DeliveryRow,s:DeliveryStatus)=>void}){return <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="text-xs text-white/35"><tr><th className="p-3">Customer</th><th className="p-3">Phone</th><th className="p-3">Type</th><th className="p-3">Meal / Order</th><th className="p-3">Time</th><th className="p-3">Location</th><th className="p-3">Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-white/5"><td className="p-3 font-semibold">{r.customerName}<span className="block text-xs text-white/35">{r.customerId}</span></td><td className="p-3">{r.phone}</td><td className="p-3">{r.planOrType}</td><td className="max-w-[260px] p-3">{r.meal}</td><td className="p-3">{r.time}</td><td className="max-w-[260px] p-3">{r.address||"—"}</td><td className="p-3"><select value={r.status} onChange={e=>onStatus(r,e.target.value as DeliveryStatus)} className="rounded-lg border border-white/10 bg-black px-3 py-2 text-xs"><option value="PENDING">Pending</option><option value="DELIVERED">Delivered</option></select></td></tr>)}</tbody></table>{rows.length===0&&<p className="p-5 text-white/40">No deliveries in this list.</p>}</div>}
