"use client";
export const dynamic = "force-dynamic";
import Image from "next/image";
import Link from "next/link";
import { Suspense, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { DAYS, getPlan } from "@/lib/subscriptionData";
import { DELIVERY_SLOTS, getDeliverySlotAvailability, type DeliverySlot } from "@/lib/deliverySlotService";
import { isSlotEligibleForNewSubscription } from "@/lib/deliverySlotRules";
import { toast } from "react-hot-toast";
import { ChevronLeft, ExternalLink, LocateFixed, MapPin, MessageSquare } from "lucide-react";
import QRCode from "react-qr-code";
import { auth } from "@/lib/firebase";

type Customizations = Record<string, { protein: number }>;
type DraftState = { name:string; phone:string; slot:DeliverySlot|""; regularSlot?:DeliverySlot|""; firstDeliverySlotOverride?:DeliverySlot|""; instructions:string; address:string; protein:number; step:number; day:(typeof DAYS)[number]; upiTransactionId:string; startDate:string; mealCustomizations:Customizations };
const DRAFT_KEY="varahi-subscription-checkout"; const UPI_VPA="rajasekar.bukke@oksbi"; const UPI_NAME="Varahi Eat & Fit";
function proteinRange(actual:number){return{min:Math.max(0,actual-2),max:actual+6};}
function isValidUpiTransactionId(value:string){return /^[A-Za-z0-9][A-Za-z0-9._-]{5,63}$/.test(value.trim());}
function dateString(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function isToday(value:string){return value===dateString(0);}

export default function SubscriptionCheckoutPage(){return <Suspense fallback={null}><SubscriptionCheckoutContent/></Suspense>}
function SubscriptionCheckoutContent(){
 const params=useSearchParams(); const plan=getPlan(params.get("plan")||"silver") as NonNullable<ReturnType<typeof getPlan>>;
 const [step,setStep]=useState(0),[day,setDay]=useState<(typeof DAYS)[number]>("MON"),[name,setName]=useState(""),[phone,setPhone]=useState(""),[slot,setSlot]=useState<DeliverySlot|"">(""),[regularSlot,setRegularSlot]=useState<DeliverySlot|"">(""),[firstDeliverySlotOverride,setFirstDeliverySlotOverride]=useState<DeliverySlot|"">(""),[slots,setSlots]=useState<Awaited<ReturnType<typeof getDeliverySlotAvailability>>>([]),[protein,setProtein]=useState(30),[instructions,setInstructions]=useState(""),[address,setAddress]=useState(""),[locationDetected,setLocationDetected]=useState(false),[detectingLocation,setDetectingLocation]=useState(false),[loading,setLoading]=useState(false),[paymentConfirmed,setPaymentConfirmed]=useState(false),[upiTransactionId,setUpiTransactionId]=useState(""),[startDate,setStartDate]=useState(dateString()),[mealCustomizations,setMealCustomizations]=useState<Customizations>({}),[slotPrompt,setSlotPrompt]=useState(false),[todayAlternatives,setTodayAlternatives]=useState<DeliverySlot[]>([]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(DRAFT_KEY)||"null") as DraftState|null;if(saved){setName(saved.name||"");setPhone(saved.phone||"");setSlot(saved.slot||"");setRegularSlot(saved.regularSlot||saved.slot||"");setFirstDeliverySlotOverride(saved.firstDeliverySlotOverride||"");setInstructions(saved.instructions||"");setAddress(saved.address||"");setDay(saved.day||"MON");setStep(typeof saved.step==="number"?saved.step:0);setProtein(Number(saved.protein)||30);setUpiTransactionId(saved.upiTransactionId||"");setStartDate(saved.startDate||dateString());setMealCustomizations(saved.mealCustomizations||{});}}catch{} getDeliverySlotAvailability().then(setSlots).catch(()=>toast.error("Unable to load delivery slot availability."));},[]);
 const meal=useMemo(()=>plan?.meals[day.toLowerCase() as keyof typeof plan.meals],[plan,day]); const range=proteinRange(meal?.protein||0); const selectedProtein=mealCustomizations[day]?.protein??meal?.protein??0;
 useEffect(()=>{if(!meal)return;setProtein(selectedProtein>=range.min&&selectedProtein<=range.max?selectedProtein:meal.protein);},[meal,range.min,range.max,selectedProtein]);
 if(!plan||!meal)return <main className="grid min-h-screen place-items-center bg-[#050505] text-white">Invalid subscription plan.</main>;
 function saveDraft(nextStep=step){localStorage.setItem(DRAFT_KEY,JSON.stringify({name,phone,slot,regularSlot,firstDeliverySlotOverride,instructions,address,protein,step:nextStep,day,upiTransactionId,startDate,mealCustomizations} satisfies DraftState));}
 function detectLocation(){if(!navigator.geolocation){toast.error("Location detection is not supported by your browser.");return;}setDetectingLocation(true);navigator.geolocation.getCurrentPosition(({coords})=>{setAddress(`https://www.google.com/maps?q=${coords.latitude},${coords.longitude}`);setLocationDetected(true);setDetectingLocation(false);toast.success("Location detected.");},()=>{setDetectingLocation(false);toast.error("Unable to detect your location. Please enter it manually.");},{enableHighAccuracy:true,timeout:15000,maximumAge:0});}
 function eligibleToday(){return DELIVERY_SLOTS.filter(v=>Boolean(slots.find(x=>x.slot===v)?.available??true)&&isSlotEligibleForNewSubscription(v,new Date(),30));}
 function chooseRegularSlot(v:DeliverySlot){setSlot(v);setRegularSlot(v);setFirstDeliverySlotOverride("");setStartDate(dateString());setSlotPrompt(false);}
 function chooseFirstDeliverySlot(v:DeliverySlot){setFirstDeliverySlotOverride(v);setStartDate(dateString());setSlotPrompt(false);}
 function chooseTomorrow(){setFirstDeliverySlotOverride("");setStartDate(dateString(1));setSlotPrompt(false);}
 function validate(){
  if(step===0){if(name.trim().length<3){toast.error("Enter your full name.");return false;}if(!/^[6-9]\d{9}$/.test(phone)){toast.error("Enter a valid 10-digit phone number.");return false;}if(!regularSlot){toast.error("Select a delivery slot.");return false;}const selected=slots.find(x=>x.slot===regularSlot);if(!selected?.available){toast.error("That delivery slot is full. Choose another slot.");return false;}if(isToday(startDate)&&!isSlotEligibleForNewSubscription(regularSlot,new Date(),30)&&!firstDeliverySlotOverride){setTodayAlternatives(eligibleToday().filter(v=>v!==regularSlot));setSlotPrompt(true);return false;}if(firstDeliverySlotOverride&&!isSlotEligibleForNewSubscription(firstDeliverySlotOverride,new Date(),30)){setTodayAlternatives(eligibleToday().filter(v=>v!==regularSlot));setSlotPrompt(true);return false;}}
  if(step===1&&(protein<range.min||protein>range.max)){toast.error(`Protein must be between ${range.min}g and ${range.max}g.`);return false;}
  if(step===3&&address.trim().length<10){toast.error("Enter your delivery address or detect your location.");return false;}
  if(step===5){if(!upiTransactionId.trim()){toast.error("Please enter your UPI Transaction ID / UTR");return false;}if(!isValidUpiTransactionId(upiTransactionId)){toast.error("Please enter a valid UPI Transaction ID / UTR.");return false;}if(!paymentConfirmed){toast.error("Please confirm that you have completed the UPI payment.");return false;}}
  return true;
 }
 async function continueStep(){if(!validate())return;const next=step<5?step+1:step;saveDraft(next);if(step<5){setStep(next);return;}await submitPayment();}
 function openUPI(){window.location.href=`upi://pay?pa=${encodeURIComponent(UPI_VPA)}&pn=${encodeURIComponent(UPI_NAME)}&am=${encodeURIComponent(String(plan.price))}&cu=INR`;}
 async function submitPayment(){if(!validate())return;setLoading(true);try{const selected=slots.find(x=>x.slot===regularSlot);if(!selected?.available)throw new Error("That delivery slot is now full. Please choose another slot.");const currentUser=auth.currentUser;const idToken=currentUser?await currentUser.getIdToken(true):"";const response=await fetch("/api/subscriptions/guest",{method:"POST",headers:{"Content-Type":"application/json",...(idToken?{Authorization:`Bearer ${idToken}`}:{})},body:JSON.stringify({name:name.trim(),phone,address,location:address.startsWith("https://www.google.com/maps?q=")?address:"",slot:regularSlot,regularSlot,firstDeliverySlotOverride:firstDeliverySlotOverride||"",firstDeliveryOverrideDate:firstDeliverySlotOverride&&isToday(startDate)?startDate:"",protein:selectedProtein,mealCustomizations,instructions,planId:plan.id,day,startDate:startDate||dateString(),upiTransactionId:upiTransactionId.trim()})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||"Unable to submit your subscription.");const subscriptionId=String(data.subscriptionId||"");if(!subscriptionId)throw new Error("Subscription was not created. Please try again.");localStorage.removeItem(DRAFT_KEY);window.location.href=`/subscriptions/payment-verification?id=${encodeURIComponent(subscriptionId)}&plan=${encodeURIComponent(plan.id)}`;}catch(error){toast.error(error instanceof Error?error.message:"Unable to submit payment");}finally{setLoading(false);}}
 const isMap=address.startsWith("https://www.google.com/maps?q=");const steps=["Customer & slot","Meal","Instructions","Location","Review","Payment"];const upiLink=`upi://pay?pa=${encodeURIComponent(UPI_VPA)}&pn=${encodeURIComponent(UPI_NAME)}&am=${encodeURIComponent(String(plan.price))}&cu=INR`;
 return <main className="min-h-screen bg-[#050505] px-5 pb-20 pt-24 text-white"><div className="mx-auto max-w-6xl"><Link href="/#subscriptions" className="mb-8 inline-flex items-center gap-2 text-sm text-white/45 hover:text-white"><ChevronLeft className="h-4 w-4"/> Plans</Link><div className="grid gap-8 lg:grid-cols-[1fr_340px]"><section><div className="mb-8 flex items-center gap-2 overflow-x-auto pb-2">{steps.map((n,i)=><div key={n} className="flex min-w-max items-center gap-2 text-xs"><span className={`flex h-7 w-7 items-center justify-center rounded-full ${i<step?"bg-[#E63946] text-white":i===step?"border border-[#E63946] text-[#E63946]":"border border-white/10 text-white/30"}`}>{i<step?"✓":i+1}</span><span className={i===step?"text-white":"text-white/30"}>{n}</span>{i<steps.length-1&&<span className="mx-1 text-white/15">—</span>}</div>)}</div><div className="rounded-[32px] border border-white/10 bg-white/[0.035] p-6 sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#E63946]">{steps[step]}</p>
 {step===0&&<><h1 className="mt-3 text-3xl font-bold">Your details</h1><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="text-sm text-white/55">Full name<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-4 text-white outline-none focus:border-[#E63946]" placeholder="Your full name"/></label><label className="text-sm text-white/55">Phone<input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,"").slice(0,10))} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-4 text-white outline-none focus:border-[#E63946]" placeholder="10-digit mobile number"/></label></div><h2 className="mt-8 text-lg font-bold">Delivery slot</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{DELIVERY_SLOTS.map(v=>{const item=slots.find(x=>x.slot===v);const available=item?.available??true;return <button type="button" key={v} disabled={!available} onClick={()=>chooseRegularSlot(v)} className={`rounded-2xl border p-4 text-left ${regularSlot===v?"border-[#E63946] bg-[#E63946]/10":"border-white/10 bg-white/[0.02]"} ${!available?"opacity-30":""}`}><p className="font-bold">{v}</p><p className="mt-1 text-xs text-white/35">{available?"Available":"Full"}</p></button>})}</div><p className="mt-3 text-xs text-white/35">If your selected regular slot has passed, you can use another eligible slot for today's first delivery. Your regular slot remains unchanged from tomorrow.</p>{slotPrompt&&<div className="mt-5 rounded-2xl border border-yellow-500/20 bg-yellow-500/5 p-5"><p className="font-semibold">Your selected delivery slot has already passed.</p><p className="mt-2 text-sm text-white/50">Choose another available slot for today's first delivery, or start your subscription tomorrow with your selected slot.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{todayAlternatives.map(v=><button key={v} type="button" onClick={()=>chooseFirstDeliverySlot(v)} className="rounded-xl border border-white/10 bg-white/[0.03] p-4 text-left hover:border-[#E63946]"><span className="font-bold">{v}</span><span className="mt-1 block text-xs text-green-300">Start today only</span></button>)}<button type="button" onClick={chooseTomorrow} className="rounded-xl border border-[#E63946]/40 bg-[#E63946]/10 p-4 text-left"><span className="font-bold">Start tomorrow</span><span className="mt-1 block text-xs text-white/45">Keep {regularSlot}</span></button></div></div>}</>}
 {step===1&&<><h1 className="mt-3 text-3xl font-bold">Customize your meal</h1><p className="mt-2 text-sm text-white/40">Customize each day's meal individually.</p><div className="mt-7 flex gap-2 overflow-x-auto">{DAYS.map(d=><button key={d} type="button" onClick={()=>setDay(d)} className={`rounded-full px-5 py-2 text-xs font-bold ${day===d?"bg-[#E63946] text-white":"bg-white/5 text-white/50"}`}>{d}</button>)}</div><div className="mt-6 grid gap-6 sm:grid-cols-[180px_1fr]"><div className="relative h-44 overflow-hidden rounded-2xl"><Image src={meal.image} alt={meal.name} fill className="object-cover" sizes="180px"/></div><div><h2 className="text-xl font-bold">{meal.name}</h2><p className="mt-2 text-sm text-white/45">Default: {meal.protein}g protein · {meal.calories} kcal</p><label className="mt-5 block text-xs text-white/45">Protein / meal<input type="number" min={range.min} max={range.max} value={protein} onChange={e=>{const v=Number(e.target.value);setProtein(v);setMealCustomizations(c=>({...c,[day]:{protein:v}}));}} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-3 text-white outline-none focus:border-[#E63946]"/></label></div></div></>}
 {step===2&&<><h1 className="mt-3 text-3xl font-bold">Any special instructions?</h1><div className="mt-8"><MessageSquare className="mb-3 h-5 w-5 text-[#E63946]"/><textarea value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Less spicy, no onion, etc." className="min-h-40 w-full rounded-2xl border border-white/10 bg-black/25 p-5 text-white outline-none placeholder:text-white/25 focus:border-[#E63946]"/></div></>}
 {step===3&&<><h1 className="mt-3 text-3xl font-bold">Where should we deliver?</h1><p className="mt-2 text-sm text-white/40">Use your current location or enter an address.</p><div className="mt-8"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><MapPin className="h-5 w-5 text-[#E63946]"/><span className="text-sm font-medium text-white/70">Delivery location</span></div>{locationDetected&&<span className="text-xs text-green-400">Location detected</span>}</div><textarea value={address} onChange={e=>{setAddress(e.target.value);setLocationDetected(false)}} placeholder="Enter your full delivery address..." className="min-h-36 w-full rounded-2xl border border-white/10 bg-black/25 p-5 text-white outline-none placeholder:text-white/25"/>{isMap&&<a href={address} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-[#E63946]">View location in Google Maps <ExternalLink className="h-3.5 w-3.5"/></a>}<button type="button" onClick={detectLocation} disabled={detectingLocation} className="mt-4 flex w-full items-center justify-center gap-3 rounded-2xl border border-[#E63946]/40 bg-[#E63946]/10 px-5 py-4 text-sm font-bold text-[#E63946] disabled:opacity-50"><LocateFixed className="h-5 w-5"/>{detectingLocation?"Detecting...":"Detect My Location"}</button></div></>}
 {step===4&&<><h1 className="mt-3 text-3xl font-bold">Review your subscription</h1><div className="mt-8 space-y-4 text-sm text-white/60"><p><b className="text-white">Plan:</b> {plan.name} · ₹{plan.price}/week</p><p><b className="text-white">Start date:</b> {startDate}</p><p><b className="text-white">Regular delivery:</b> {regularSlot}</p>{firstDeliverySlotOverride&&isToday(startDate)&&<p><b className="text-white">Today's first delivery:</b> {firstDeliverySlotOverride}</p>}<p><b className="text-white">Address:</b> {isMap?<a href={address} target="_blank" rel="noopener noreferrer" className="text-[#E63946]">Open Google Maps location</a>:address}</p><p><b className="text-white">Instructions:</b> {instructions||"None"}</p></div></>}
 {step===5&&<><h1 className="mt-3 text-3xl font-bold">Pay with UPI</h1><div className="mt-8 rounded-2xl border border-white/10 bg-black/20 p-6"><p className="text-sm text-white/60">Pay ₹{plan.price} to <b className="text-white">{UPI_VPA}</b></p><div className="mt-6 flex justify-center"><div className="rounded-2xl bg-white p-4"><QRCode value={upiLink} size={220}/></div></div><p className="mt-4 text-center text-sm font-semibold">Scan this QR code with any UPI app</p><button type="button" onClick={openUPI} className="mt-6 w-full rounded-2xl bg-[#E63946] px-5 py-4 font-bold">Open UPI App</button><label className="mt-4 block text-sm font-semibold text-white/80">UPI Transaction ID / UTR<input value={upiTransactionId} onChange={e=>setUpiTransactionId(e.target.value.replace(/\s/g,"").slice(0,64))} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-4 text-white outline-none" placeholder="Enter your UPI Transaction ID / UTR"/></label><label className="mt-4 flex cursor-pointer items-center gap-3 rounded-xl border border-white/10 bg-white/[0.03] p-4 text-sm font-semibold"><input type="checkbox" checked={paymentConfirmed} onChange={e=>setPaymentConfirmed(e.target.checked)} className="h-5 w-5 accent-[#E63946]"/>I've Completed Payment</label></div></>}
 <div className="mt-10 flex justify-between gap-3"><button type="button" disabled={step===0||loading} onClick={()=>setStep(Math.max(0,step-1))} className="rounded-full border border-white/10 px-6 py-3 text-sm disabled:opacity-20">Back</button><button type="button" disabled={loading||detectingLocation} onClick={continueStep} className="rounded-full bg-[#E63946] px-7 py-3 text-sm font-bold disabled:opacity-50">{loading?"Submitting...":step===5?"Submit Payment":"Continue"}</button></div></div></section><aside className="h-fit rounded-[28px] border border-white/10 bg-[#0D0B0B] p-6"><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#E63946]">Summary</p><h2 className="mt-3 text-2xl font-bold">{plan.name} Plan</h2><p className="mt-1 text-sm text-white/40">7-day nutrition plan</p><div className="my-7 border-y border-white/10 py-5"><div className="flex justify-between text-sm"><span className="text-white/45">Weekly total</span><b>₹{plan.price}</b></div><div className="mt-3 flex justify-between text-sm"><span className="text-white/45">Start date</span><span>{startDate}</span></div><div className="mt-3 flex justify-between text-sm"><span className="text-white/45">Delivery slot</span><span>{firstDeliverySlotOverride&&isToday(startDate)?firstDeliverySlotOverride:(regularSlot||"Not selected")}</span></div></div><p className="text-xs leading-5 text-white/35">After you complete the UPI payment, submit it for manual verification.</p></aside></div></div></main>;
}
